branch-defaults:
  master:
    environment: ydm-api
global:
  application_name: ydm
  default_ec2_keyname: aws-eb
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running PHP 7.0
  default_region: eu-west-1
  profile: eb-cli
  sc: git
